### ISSUE TITLE
Some events don't have end time

### ISSUE THREAD

**Issue by patkarns** [mostlyfabulous/Runtime#24]

**Comment by patkarns** [comment]
1. Some events don't have end time (end: null).
2.  Data types for end time inconsistent (date vs. string, see screenshot below).
![image](https://user-images.githubusercontent.com/30379111/61582070-fd410500-aada-11e9-9a0d-c949ba02165f.png)

**Comment by patkarns** [comment]
I used this code to format my date string to a date object:
`let endTime = moment(suggestions[0]).add(duration, 'minutes').format();
    let endTimeUNIX = Date.parse(endTime);
    let endTimeFormatted = new Date(endTimeUNIX);`

**Comment by mostlyfabulous** [comment]
Removed all old events that had no endtime
